In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df_train=pd.read_csv('D:\DATASET\House Price Prediction\Bengaluru_House_Data.csv')

In [ ]:
df_train.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [ ]:
df_train.shape

(13320, 9)

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [ ]:
for column in df_train.columns:
    print(df_train[column].value_counts())
    print("*"*20)

Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: area_type, dtype: int64
********************
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
15-Aug               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: availability, Length: 81, dtype: int64
********************
Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: location, Length: 1305, dtype: int64
********************
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
14 BHK           1
13 BHK           1
12 Bedroom       1
27 BHK           1
43 Bedroom       1
16 BHK           1
19 BHK           1
18 Bedroom       1
Name: size, dtype: int64
********************
GrrvaGr    80
PrarePa    76
Sryalan    59
Prtates    59
GMown E    56
           ..
Amionce     1
JaghtDe     1
Jauraht     1
Brity U     1
RSntsAp     1
Name: society, Length: 2688, dtype: int64
********************
1200    843
1100    221
1500    205
2400    196
600     180
       ...
3580      1
2461      1
1437      1
2155      1
4689      1
Name: total_sqft, Length: 2117, dtype: int64
********************
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
13.0       3
11.0       3
16.0       2
27.0       1
40.0       1
15.0       1
14.0       1
18.0       1
Name: bath, dtype: int64
********************
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: balcony, dtype: int64
********************
75.00     310
65.00     302
55.00     275
60.00     270
45.00     240
         ...
351.00      1
54.10       1
80.64       1
32.73       1
488.00      1
Name: price, Length: 1994, dtype: int64
********************

In [ ]:
df_train.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [ ]:
df_train.drop(columns=['area_type','availability','society','balcony'],inplace=True)

In [ ]:
df_train.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [ ]:
df_train['location'].value_counts()

Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: location, Length: 1305, dtype: int64

In [ ]:
df_train['location']=df_train['location'].fillna('Sarjapur Road')

In [ ]:
df_train['size'].value_counts()

2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
14 BHK           1
13 BHK           1
12 Bedroom       1
27 BHK           1
43 Bedroom       1
16 BHK           1
19 BHK           1
18 Bedroom       1
Name: size, dtype: int64

In [ ]:
df_train['size'] = df_train['size'].fillna('2 BHK')

In [ ]:
df_train['bath'] = df_train['bath'].fillna(df_train['bath'].median())

In [ ]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   size        13320 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13320 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [ ]:
df_train['BHK']=df_train['size'].str.split().str.get(0).astype(int)

In [ ]:
df_train[df_train.BHK > 20]

                       location        size total_sqft  bath  price  BHK
1718  2Electronic City Phase II      27 BHK       8000  27.0  230.0   27
4684                Munnekollal  43 Bedroom       2400  40.0  660.0   43

In [ ]:
df_train['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [ ]:
def convertRange(x):
    
    temp = x.split('_')
    if len(temp) == 2:
        return(float(temp[0])+float(temp[1]))/2
    try:
        return float(x)
    except:
        return None

In [ ]:
df_train['total_sqft'] = df_train['total_sqft'].apply(convertRange)

In [ ]:
df_train.head()

                   location       size  total_sqft  bath   price  BHK
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2

# Price Per Square feet

In [ ]:
df_train['price_per_sqft']=df_train['price'] = 100000 / df_train['total_sqft']

In [ ]:
df_train['price_per_sqft']

0         94.696970
1         38.461538
2         69.444444
3         65.746220
4         83.333333
            ...
13315     28.960324
13316     27.777778
13317     87.642419
13318     21.326509
13319    181.818182
Name: price_per_sqft, Length: 13320, dtype: float64

In [ ]:
df_train.describe()

         total_sqft          bath          price           BHK  price_per_sqft
count  13073.000000  13320.000000   13073.000000  13320.000000    13073.000000
mean    1554.942029      2.688814      90.246815      2.802778       90.246815
std     1238.458773      1.338754     898.070032      1.294496      898.070032
min        1.000000      1.000000       1.913070      1.000000        1.913070
25%     1100.000000      2.000000      59.880240      2.000000       59.880240
50%     1275.000000      2.000000      78.431373      3.000000       78.431373
75%     1670.000000      3.000000      90.909091      3.000000       90.909091
max    52272.000000     40.000000  100000.000000     43.000000   100000.000000

In [ ]:
df_train['location'].value_counts()

Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Uvce Layout                         1
Abshot Layout                       1
Name: location, Length: 1306, dtype: int64

In [ ]:
df_train['location'] = df_train['location'].apply(lambda x: x.strip())
location_count=df_train['location'].value_counts()

In [ ]:
location_count

Whitefield                            541
Sarjapur  Road                        399
Electronic City                       304
Kanakpura Road                        273
Thanisandra                           237
                                     ...
1Channasandra                           1
Hosahalli                               1
Vijayabank bank layout                  1
near Ramanashree California resort      1
Abshot Layout                           1
Name: location, Length: 1295, dtype: int64

In [ ]:
location_count_less_10 = location_count[location_count<=100]
location_count_less_10

Chandapura                            100
Bellandur                              96
KR Puram                               91
Hoodi                                  88
Electronics City Phase 1               88
                                     ...
1Channasandra                           1
Hosahalli                               1
Vijayabank bank layout                  1
near Ramanashree California resort      1
Abshot Layout                           1
Name: location, Length: 1279, dtype: int64

In [ ]:
df_train['location'] = df_train['location'].apply(lambda x: 'other' if x in location_count_less_10 else x)

In [ ]:
df_train['location'].value_counts()

other                       9810
Whitefield                   541
Sarjapur  Road               399
Electronic City              304
Kanakpura Road               273
Thanisandra                  237
Yelahanka                    213
Uttarahalli                  186
Hebbal                       177
Marathahalli                 175
Raja Rajeshwari Nagar        171
Hennur Road                  152
Bannerghatta Road            152
7th Phase JP Nagar           149
Haralur Road                 142
Electronic City Phase II     132
Rajaji Nagar                 107
Name: location, dtype: int64

# Outlier detection and removal

In [ ]:
df_train.describe()

         total_sqft          bath          price           BHK  price_per_sqft
count  13073.000000  13320.000000   13073.000000  13320.000000    13073.000000
mean    1554.942029      2.688814      90.246815      2.802778       90.246815
std     1238.458773      1.338754     898.070032      1.294496      898.070032
min        1.000000      1.000000       1.913070      1.000000        1.913070
25%     1100.000000      2.000000      59.880240      2.000000       59.880240
50%     1275.000000      2.000000      78.431373      3.000000       78.431373
75%     1670.000000      3.000000      90.909091      3.000000       90.909091
max    52272.000000     40.000000  100000.000000     43.000000   100000.000000

In [ ]:
(df_train['total_sqft']/df_train['BHK']).describe()

count    13073.000000
mean       573.254923
std        389.887823
min          0.250000
25%        472.000000
50%        551.000000
75%        625.000000
max      26136.000000
dtype: float64

In [ ]:
df_train = df_train[((df_train['total_sqft']/df_train['BHK'])>=300)]
df_train.describe()

         total_sqft          bath         price           BHK  price_per_sqft
count  12329.000000  12329.000000  12329.000000  12329.000000    12329.000000
mean    1590.166773      2.561441     76.938542      2.651472       76.938542
std     1261.827604      1.072551     31.477411      0.973754       31.477411
min      300.000000      1.000000      1.913070      1.000000        1.913070
25%     1118.000000      2.000000     58.823529      2.000000       58.823529
50%     1300.000000      2.000000     76.923077      3.000000       76.923077
75%     1700.000000      3.000000     89.445438      3.000000       89.445438
max    52272.000000     16.000000    333.333333     16.000000      333.333333

In [ ]:
df_train.shape

(12329, 7)

In [ ]:
df_train.price_per_sqft.describe()

count    12329.000000
mean        76.938542
std         31.477411
min          1.913070
25%         58.823529
50%         76.923077
75%         89.445438
max        333.333333
Name: price_per_sqft, dtype: float64

In [ ]:
def remove_outliers_sqft(df):
    df_output = pd.DataFrame()
    for key,subdf in df.groupby('location'):
        m = np.mean(subdf.price_per_sqft)
        
        st = np.std(subdf.price_per_sqft)
        
        gen_df = subdf[(subdf.price_per_sqft > (m-st)) & (subdf.price_per_sqft <= (m+st))]
        df_output = pd.concat([df_output,gen_df],ignore_index = True)
    return df_output
df_train = remove_outliers_sqft(df_train)
df_train.describe()

        total_sqft         bath        price          BHK  price_per_sqft
count  9482.000000  9482.000000  9482.000000  9482.000000     9482.000000
mean   1367.151637     2.398228    76.345150     2.543345       76.345150
std     299.740980     0.659390    15.033498     0.633479       15.033498
min     800.000000     1.000000    32.258065     1.000000       32.258065
25%    1150.000000     2.000000    64.516129     2.000000       64.516129
50%    1280.000000     2.000000    78.125000     2.000000       78.125000
75%    1550.000000     3.000000    86.956522     3.000000       86.956522
max    3100.000000     8.000000   125.000000     7.000000      125.000000

In [ ]:
def BHK_outlier_remover(df):
    exclude_indices = np.array([])
    for location, location_df in df.groupby('location'):
        BHK_stats = {}
        for BHK, BHK_df in location_df.groupby('BHK'):
            BHK_stats[BHK] = {
                'mean': np.mean(BHK_df.price_per_sqft),
                'std' : np.std(BHK_df.price_per_sqft),
                'count': BHK_df.shape[0]
            }
        for BHK, BHK_df in location_df.groupby('BHK'):
            stats = BHK_stats.get(BHK-1)
            if stats and stats['count']>5:
                exclude_indices = np.append(exclude_indices, BHK_df[BHK_df.price_per_sqft<(stats['mean'])].index.vlaues)
            return df.drop(exclude_indices,axis='index')

In [ ]:
df_train = BHK_outlier_remover(df_train)

In [ ]:
df_train.shape

(9482, 7)

In [ ]:
df_train

,location,size,total_sqft,bath,price,BHK,price_per_sqft
0,7th Phase JP Nagar,2 BHK,1080.0,2.0,92.592593,2,92.592593
1,7th Phase JP Nagar,2 BHK,1270.0,2.0,78.740157,2,78.740157
2,7th Phase JP Nagar,3 BHK,1420.0,2.0,70.422535,3,70.422535
3,7th Phase JP Nagar,3 BHK,1850.0,3.0,54.054054,3,54.054054
4,7th Phase JP Nagar,2 BHK,1245.0,2.0,80.321285,2,80.321285
...,...,...,...,...,...,...,...
9477,other,3 BHK,1805.0,3.0,55.401662,3,55.401662
9478,other,3 BHK,1675.0,3.0,59.701493,3,59.701493
9479,other,2 BHK,1050.0,2.0,95.238095,2,95.238095
9480,other,2 BHK,1262.0,2.0,79.239303,2,79.239303
9481,other,3 BHK,1715.0,3.0,58.309038,3,58.309038

In [ ]:
df_train.drop(columns=['size','price_per_sqft'],inplace = True)

# Cleaned Data

In [ ]:
df_train.head()

             location  total_sqft  bath      price  BHK
0  7th Phase JP Nagar      1080.0   2.0  92.592593    2
1  7th Phase JP Nagar      1270.0   2.0  78.740157    2
2  7th Phase JP Nagar      1420.0   2.0  70.422535    3
3  7th Phase JP Nagar      1850.0   3.0  54.054054    3
4  7th Phase JP Nagar      1245.0   2.0  80.321285    2

In [ ]:
df_train.to_csv("Cleaned_data_01.csv")

In [ ]:
X=df_train.drop(columns=['price'])
y=df_train['price']

# Linear Regression

In [ ]:
#Import necessary libraries
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)

In [ ]:
print(X_train.shape)
print(X_test.shape)

(7585, 4)
(1897, 4)

In [ ]:
#Create a column transformer that applies one-hot encoding to the 'location' column and passes through the remaining columns
column_trans = make_column_transformer((OneHotEncoder(sparse=False),['location']),remainder = 'passthrough')

In [ ]:
#Create a scaler to standardize the input features
scaler = StandardScaler()

In [ ]:
#Create a linear regression model with normalization
lr = LinearRegression(normalize=True)

In [ ]:
#Create a pipeline that applies the column transformer, scaler, and linear regression model in sequence
pipe = make_pipeline(column_trans,scaler,lr)

In [ ]:
#Fit the pipeline to the training data
pipe.fit(X_train,y_train)

C:\Users\alish\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression(normalize=True))])

In [ ]:
#Make predictions on the test data using the fitted pipeline
y_pred_lr = pipe.predict(X_test)

In [ ]:
#Compute the R-squared score on the test data
r2_score(y_test,y_pred_lr)

0.9452274656057931

# Lasso

In [ ]:
#import lasso regression model
lasso = Lasso()

In [ ]:
#create pipeline to preprocess data and apply lasso regression
pipe = make_pipeline(column_trans,scaler,lasso)

In [ ]:
#Fit pipeline on training data
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('lasso', Lasso())])

In [ ]:
#Use pipeline to make predictions on test data
y_pred_lasso = pipe.predict(X_test)
r2_score(y_test, y_pred_lasso) #calculate R-squared score

0.9318712677067

# Ridge

In [ ]:
#Define ridge regression model
ridge = Ridge()

In [ ]:
#create a pipeline that applies the column transformation step, scaling step, and then the ridge regression model
pipe = make_pipeline(column_trans,scaler,ridge)

In [ ]:
#fit the pipeline on the training data
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('ridge', Ridge())])

In [ ]:
#make predictions on the test data using the pipeline
y_pred_ridge = pipe.predict(X_test)
#calculate the R-squared score on the test data using the ridge regression model
r2_score(y_test,y_pred_ridge)

0.945154069298924

In [ ]:
#calculate the R-squared score on the test data using the simple linear regression model
print("No Regularization: ",r2_score(y_test,y_pred_lr))
#Calculate the R-squared score on the test data using the Lasso regression model
print("Lasso: ",r2_score(y_test,y_pred_lasso))
#calculate the R-squared score on the test data using the lasso regression model
print("Ridge: ",r2_score(y_test,y_pred_ridge))

No Regularization:  0.9452274656057931
Lasso:  0.9318712677067
Ridge:  0.945154069298924

In [ ]:
import pickle

In [ ]:
pickle.dump(pipe, open('RidgeModel_01.pkl','wb'))